#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE SAP 
# Description: Gathers important troubleshooting information
#              about a SUSE SAP HANA/NetWeaver configurations
# License:     GPLv2
#############################################################

SVER='1.0.5'
RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
TITLE="SUSE SAP"
INSTANCES=()

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

validate_rpm_if_installed() {
	THISRPM=$1
	echo "#==[ Validating RPM ]=================================#"
	if rpm -q $THISRPM >/dev/null 2>&1; then
		echo "# rpm -V $THISRPM"
		if rpm -V $THISRPM; then
			echo "Status: Passed"
		else
			echo "Status: WARNING"
		fi
	else
		echo "package $THISRPM is not installed"
		echo "Status: Skipped"
	fi
	echo
}

collect_instance_log() {
	local LFILE
	for LFILE in "${@}" ; do
		echo "#==[ instance Log File '$LFILE' ]=============#"
		echo "# ${LFILE}"
		cat "${LFILE}"
		echo "######"
	done
}

## Docs  ##
section_header "Referencee Documentation"
echo -e "Current Documentation:
\t https://documentation.suse.com/en-us/sles-sap/15-SP5/
\t https://documentation.suse.com/en-us/sles-sap/15-SP4/
\t https://documentation.suse.com/en-us/sles-sap/15-SP3/
\t https://documentation.suse.com/en-us/sles-sap/15-SP2/
\t https://documentation.suse.com/en-us/sles-sap/15-SP1/

Tuning: 
\t https:://documentation.suse.com/sles-sap/15-SP5/single-html/SLES-SAP-guide/index.html#cha-tune

Best Practice Guides: \t https://documentation.suse.com/sbp/sap/
\tSAP HANA SR Performance Optimized Scale up:\t https://documentation.suse.com/sbp/sap-15/pdf/SLES4SAP-hana-sr-guide-PerfOpt-15_en.pdf
\tSAP HANA SR Performance Optimized Scale out:\t https://documentation.suse.com/sbp/sap-15/pdf/SLES4SAP-hana-scaleOut-PerfOpt-15_en.pdf
\tSAP HANA SR Performance Optimized Scale out Multi-Target:\t https://documentation.suse.com/sbp/sap-15/pdf/SLES4SAP-hana-scaleout-multitarget-perfopt-15_en.pdf
\tSAP HANA SR Cost Optimized Scale Up:\t https://documentation.suse.com/sbp/sap-15/pdf/SLES4SAP-hana-sr-guide-costopt-15_en.pdf
\tENSA1 SAP NetWeaver Enqueue Replication:\t https://documentation.suse.com/sbp/sap-15/pdf/SAP-nw740-sle15-setupguide_en.pdf
\tENSA2 SAP S/4 HANA - Enqueue Replication:\t https://documentation.suse.com/sbp/sap-15/pdf/SAP-S4HA10-setupguide-simplemount-sle15_en.pdf
"
#############################################################
section_header "Supportconfig Plugin for $TITLE, v${SVER}"
RPMLIST="
SAPHanaSR
sapconf
tuned
saptune
sap-suse-cluster-connector
sap_suse_cluster_connector
SAPHanaSR-ScaleOut
resource-agents
sapstartsrv-resource-agents
"

for THISRPM in $RPMLIST; do
	validate_rpm_if_installed $THISRPM
done
## Authentication ## 
section_header "Authentication information"
	plugin_command "grep -v '^\s*\#\|^$' /etc/nsswitch.conf | head -5"
	plugin_command "grep -E '^[[:alnum:]]{3}adm:' /etc/passwd"
	plugin_command "grep -E '^sap' /etc/passwd"
	plugin_command "grep -E '^[[:alnum:]]{3}adm:' /etc/group"
	plugin_command "grep -E -e '^sap' -e '^sdba:' -e '^dba:' /etc/group"
	plugin_command "grep -E -R -e '[[:alnum:]]{3}adm' -e 'crm_attribute' -e 'SAPHanaSR' /etc/sudoers /etc/sudoers.d/"

## SAP BASIC Tuning ##
section_header "SAP Tuning information"

RELEASE=$(grep ^VERSION= /etc/os-release)
echo -e  "OS Release: $RELEASE \n"
if [ $RELEASE == 'VERSION="11.4"' ]; then
	plugin_command "chkconfig -l boot.sapconf"
	plugin_command "cat /etc/sysconfig/sapconf | grep -v '^\s*\#\|^$'"
else 
	plugin_command "systemctl status sapconf"
	plugin_command "systemctl status tuned.service"
	if [ $? -eq 0 ]
	then
		noSaptuneProfile="true"
		plugin_command "tuned-adm active"
		if [ $? -eq 0 ]; then
			profile=$(cat /etc/tuned/active_profile)
			if [ "$profile" == "saptune" ]; then
				plugin_command "saptune version"
				plugin_command "saptune solution list"
				plugin_command "saptune note list"
				plugin_command "saptune solution verify"
				noSaptuneProfile=""
			fi
		fi
	else
		noTuned="true"
        fi
	plugin_command "systemctl status saptune.service"
	if [ $? -eq 0 ]; then
		plugin_command "saptune version"
		echo -e "HINT: since saptune 3.0 a special saptune supportconfig plugin exists\n"
		plugin_command "saptune status"
		plugin_command "saptune solution list"
		plugin_command "saptune note list"
		plugin_command "saptune solution verify"
	else
		noSaptune="true"
	fi
	if [[ "$noSaptune" == "true"  && ( "$noTuned" == "true" || "$noSaptuneProfile" == "true" ) ]]; then
		echo "WARNING: tuned.service or saptune not configured"
	fi
fi 

## SAP Host Agent ##
section_header "SAP Host Agent Information"
plugin_command "/usr/sap/hostctrl/exe/saphostexec -version |tail -30"
plugin_command "/usr/sap/hostctrl/exe/saphostexec -status"
     if [ $? -eq 1 ]
     then
        echo -e "ERROR: Please make sure 'sapinit.service' is enabled and running. \n"
     fi
plugin_command "systemctl status sapinit"
plugin_command "/usr/bin/cat /usr/sap/sapservices"
plugin_command "systemctl status saphostagent.service"
plugin_command "systemctl status sapping.service"
plugin_command "systemctl status sappong.service"
plugin_command "systemctl list-unit-files | grep -i sap"
plugin_command "systemd-cgls -u SAP.slice"

## SAP Exit Code Index ##
SAPCONTROLEXIT="sapcontrol return codes: \n 
  0  Last webmethod call successful \n 
  1  Last webmethod call failed, invalid parameter \n 
  2  StartWait, StopWait, WaitforStarted, WaitforStopped, RestartServiceWait timed out \n 
  3  GetProcessList succeeded, all processes running correctly \n 
  4  GetProcessList succeeded, all processes stopped \n"
SAPHDB1="lanscapeHostConfiguration.py return codes: \n 
  0  Fatal \n 
  1  Error \n
  2  Warning \n 
  3  Info \n 
  4  OK \n 
  5  Ignore \n"
SAPHDB2="systemReplicationStatus.py return codes: \n 
  10  NoHSR \n
  11  Error \n 
  12  Unknown ( Normal rc for Secondaray/slave node ) \n 
  13  Initializing \n 
  14  Syncing \n 
  15  Active ( Desired state for Primary/master node ) \n"

ENSAMSG1="## ENSA1 ##  (Default Standalone Enqueue Server) \n
    Service names: 'msg_server', 'enserver', and 'enrepserver' \n
    Process names: 'ms.sap*', 'er.sap*' \n"
ENSAMSG2="## ENSA2 ##  (Default starting with S/4HANA ABAP Platform 1809) \n
    Service names: 'msg_server', 'enq_server', and 'enq_replicator' \n
    Process names: 'ms.sap*', 'enq.sap*', 'enqr.sap*' \n"

section_header "$TITLE retrieve SAP Instances"
# Get SAP Instances using saphostctrl function. Relies on sap interface to be working. 
SAP_CONFIG="sap_config.txt"
if [ -x /usr/sap/hostctrl/exe/saphostctrl ]; then
	/usr/sap/hostctrl/exe/saphostctrl -function ListInstances | awk '{print $4,$6}' &> $SAP_CONFIG

	while read LINE
	do
		SID=$(echo $LINE | awk '{print $1}')
		SIDADM="$(tr '[:upper:]' '[:lower:]' <<< $SID)adm"
		INST=$(echo $LINE | awk '{print $2}')
		INST_NAME="SID=$SID:InstanceNumber=$INST"
		INSTANCES+=("${INST_NAME} ${SIDADM} ${SID} ${INST}")
	done < $SAP_CONFIG
	rm -r $SAP_CONFIG
fi

if [ -z "$SID" ]; then
	if [ -x /usr/sap/sapservices ]; then
		# saphostctrl does not report instances, search for systemd services
		# or read from /usr/sap/sapservices
		sapservices=$(systemctl -t service list-unit-files | sed -n 's/\(^SAP.*\).service.*/\1/p')
		if [ -z "$sapservices" ]; then
			# no systemd services available, try /usr/sap/sapservices
			sapservices=$(awk '$1!~/^#/ {print $3}' /usr/sap/sapservices | awk -F= '{print $2}')
			for s in $sapservices; do
				# /usr/sap/HA1/SYS/profile/HA1_HDB10_node11
				service=${s##*/}
				SID=${service:0:3}
				SIDADM=${SID,,}adm
				INST=${service:7:2}
				INST_NAME="SID=$SID:InstanceNumber=$INST"
				INSTANCES+=("${INST_NAME} ${SIDADM} ${SID} ${INST}")
			done
		else
			# SAP naming schema for services - SAP<SID>_<INSTNO>.service
			for service in $sapservices; do
				# SAPHA1_00
				SID=${service:3:3}
				SIDADM=${SID,,}adm
				INST=${service:7:2}
				INST_NAME="SID=$SID:InstanceNumber=$INST"
				INSTANCES+=("${INST_NAME} ${SIDADM} ${SID} ${INST}")
			done
		fi
	else
		echo -e "ERROR: No SIDs found! \n"
		
	fi
fi

section_header "$TITLE Troubleshooting Commands"
plugin_command "/usr/sap/hostctrl/exe/saphostctrl -function ListInstances"
if [ -n "$SIDADM" ]; then
	plugin_command "ps -U $SIDADM -f"
fi

# Run through each instance detected and display information about it
VHOST=$(hostname)
INST_CNT=1
LABEL=0
ADM=1
SID=2
NUM=3
for INSTANCE in "${INSTANCES[@]}"
do
	# take the INSTANCE variable and turn it into a new array called ELEMENT. Rather than refer to the items in the array by their numeric placement the above 4 variables will be used as reference.
	read -r -a ELEMENT <<< $INSTANCE
	section_header "$TITLE Instance $INST_CNT of ${#INSTANCES[@]}: ${ELEMENT[${LABEL}]}"
	HDBEXIST=true
	plugin_command "su - ${ELEMENT[${ADM}]} -c 'HDB version'"
	plugin_command "su - ${ELEMENT[${ADM}]} -c 'python --version'"
	plugin_command "/usr/bin/id ${ELEMENT[${ADM}]}"
	if [[ $? == 0 ]]; then
		echo "RETURN CODE: $?"; echo
		plugin_command "SAPHanaSR-monitor"
		echo "RETURN_CODE: $?"; echo 
		plugin_command "SAPHanaSR-showAttr"
		echo "RETURN_CODE: $?"; echo 
		plugin_command "su - ${ELEMENT[${ADM}]} -c 'hdbnsutil -sr_state'"
		echo "RETURN CODE: $?"; echo
		plugin_command "su - ${ELEMENT[${ADM}]} -c 'HDBSettings.sh landscapeHostConfiguration.py --sapcontrol=1'"
		echo "RETURN CODE: $?"; echo -e $SAPHDB1; echo
		plugin_command "su - ${ELEMENT[${ADM}]} -c 'HDBSettings.sh systemReplicationStatus.py'"
		echo "RETURN CODE: $?"; echo -e $SAPHDB2; echo
		plugin_command "su - ${ELEMENT[${ADM}]} -c 'HDBSettings.sh systemOverview.py'"
		echo "RETURN CODE: $?"; echo
		plugin_command "su - ${ELEMENT[${ADM}]} -c 'HDB info'"
		echo "RETURN CODE: $?"; echo
	else
		echo "RETURN CODE: $?"; echo
		HDBEXIST=false
	fi
	plugin_command "su - ${ELEMENT[${ADM}]} -c 'sapcontrol -nr ${ELEMENT[${NUM}]} -function GetStartProfile'"
	plugin_command "su - ${ELEMENT[${ADM}]} -c 'sapcontrol -nr ${ELEMENT[${NUM}]} -function GetSystemInstanceList'"
	plugin_command "su - ${ELEMENT[${ADM}]} -c 'sapcontrol -nr ${ELEMENT[${NUM}]} -function GetProcessList'"
	echo "RETURN CODE: $?"; echo -e $SAPCONTROLEXIT; echo; echo -e $ENSAMSG1; echo -e $ENSAMSG2

	INSTANCE_PROFILE_DIR=$(su - ${ELEMENT[${ADM}]} -c 'cdpro && pwd' 2>/dev/null)
	INSTANCE_CONFIG_DIR=$(su - ${ELEMENT[${ADM}]} -c 'cdcoc && pwd' 2>/dev/null)
	if [[ -d $INSTANCE_CONFIG_DIR ]] && [[ $HDBEXIST == true ]]; then
		pconf_files ${INSTANCE_CONFIG_DIR}/global.ini ${INSTANCE_CONFIG_DIR}/nameserver.ini ${INSTANCE_CONFIG_DIR}/daemon.ini
	fi
	if [[ -d $INSTANCE_PROFILE_DIR ]]; then
		pconf_files ${INSTANCE_PROFILE_DIR}/${ELEMENT[${SID}]}_*
	fi
	
	plugin_command "systemctl status SAP${ELEMENT[${SID}]}_${ELEMENT[${NUM}]}.service"

	# SUSE HANA hook script logs
	# /usr/sap/HA1/HDB10/hanacost1/trace/nameserver_suschksrv.trc
	lfile=/usr/sap/${ELEMENT[${SID}]}/HDB${ELEMENT[${NUM}]}/${VHOST}/trace/nameserver_suschksrv.trc
	collect_instance_log ${lfile}
	# /usr/sap/HA1/HDB10/hanacost1/trace/nameserver_saphanasr_multitarget_hook.trc
	lfile=/usr/sap/${ELEMENT[${SID}]}/HDB${ELEMENT[${NUM}]}/${VHOST}/trace/nameserver_saphanasr_multitarget_hook.trc
	collect_instance_log ${lfile}

	## Adding support for sap-suse-cluster-connector  ##
        plugin_command "rpm -qa | grep -E 'sap-suse-cluster-connector|sap_suse_cluster_connector'"
        if [ $? -eq 0 ]; then
                plugin_command "su - ${ELEMENT[${ADM}]} -c 'sapcontrol -nr ${ELEMENT[${NUM}]} -function HAGetFailoverConfig'"
                echo "RETURN CODE: $?"; echo 
                plugin_command "su - ${ELEMENT[${ADM}]} -c 'sapcontrol -nr ${ELEMENT[${NUM}]} -function HACheckFailoverConfig'"
                echo "RETURN CODE: $?"; echo 
                plugin_command "su - ${ELEMENT[${ADM}]} -c 'sapcontrol -nr ${ELEMENT[${NUM}]} -function HACheckConfig'"
                echo "RETURN CODE: $?"; echo 

		# collect instance logs
		# /usr/sap/EN2/ASCS00/work/sap_suse_cluster_connector.[old|log]
		lfile=/usr/sap/${ELEMENT[${SID}]}/ASCS${ELEMENT[${NUM}]}/work/sap_suse_cluster_connector.???
		collect_instance_log ${lfile}
		# /usr/sap/EN2/ASCS00/work/sapstartsrv.???
		lfile=/usr/sap/${ELEMENT[${SID}]}/ASCS${ELEMENT[${NUM}]}/work/sapstartsrv.???
		collect_instance_log ${lfile}
        fi

	 INST_CNT=$[ INST_CNT + 1 ]
done
## Adding some basic cluster commands.  Refer to ha.txt in supportconfig for additional ##
section_header "$TITLE Basic Cluster Configuration"
	plugin_command "crm_mon -A -r -1"
	plugin_command "crm configure show obscure:passw*"

section_header "$TITLE Log Files"
        plugin_command "grep -E -i 'saphana|SAPDatabase|SAPInstance|SAPStartsrv|sapcontrol|saphostctrl|sap_suse_cluster_connector' /var/log/messages | tail -1000"
        if ! [ $RELEASE == 'VERSION="11.4"' ]; then
                plugin_command "find /var/log/ -name pacemaker.log -exec grep -E -i 'saphana|SAPDatabase|SAPInstance|SAPStartsrv|sapcontrol|saphostctrl' {} \; | tail -1000"
        fi
